### ISSUE TITLE
Definición clasificación en SVMs

### ISSUE THREAD

**Issue by gerdm** [analysic-nabla-bootcamp/machine-learning#2]
¿Será necesario definir qué es un problema de clasificación? Quedaría mejor en lec01

https://github.com/analysic-nabla-bootcamp/machine-learning/blob/d566a84465cbad5c78f44583c20997d48679a0e8/notas/svm/svms.tex#L99

**Comment by edavme11** [comment]
Si, creo que sería conveniente definir o al menos indicar explícitamente qué es un problema de clasificación y qué es un problema de regresión.

**Comment by gerdm** [comment]
De acuerdo con eso, pero sería más apropiado tener esas definiciones dentro del primer capítulo y referirnos a esa sección.

**Comment by edavme11** [comment]
Cierto, sería mejor así.
